---
title: "DATA605 - Discussion 6"
author: "Nick Oliver"
output:
  pdf_document:
    latex_engine: xelatex
    extra_dependencies: ["geometry", "multicol", "multirow"]
editor_options: 
  chunk_output_type: console
---

# Discussion 6



## 4 Using the relation Equation 3.1 write a program to compute Pascal’s triangle, putting the results in a matrix. Have your program print the triangle for n = 10 (Chapter 3, Pg. 113)


\[
\binom{n}{j} = \binom{n-1}{j} + \binom{n-1}{j-1}
\]


```{r}
pascals_triangle <- function(height){
  #define a matrix to hold our results with height + 1 rows and columns
  m <- matrix(nrow=height+1,ncol = height+1)
  #starting at row 1 loop until you reach the height +1
  for (n in 1:(height+1)) {
    row <- "" #define empty string as row
    for(j in 1:n){#loop across columns until you reach row number
      if(j == 1 || j == n){#if first column or last column set value to 1
        m[n,j] <- 1
        row <- paste(row, m[n,j], sep = ' ')
      
      } 
      else{ #else apply formula 3.1 by looking up previous values from matrix and doing simple addition
        m[n,j] <- m[n-1, j] + m[n-1,j-1]
				row <- paste(row,m[n,j], sep = ' ')
      }
    }
    print(row)
  }
}
pascals_triangle(10)
```

```{r}
pascalTriangle <- function(h) {
  lapply(0:h, function(i) choose(i, 0:i))
}
pascalTriangle(10)
```